version: '3'
services:
  react-app:
    build:
      context: ./react-app
    ports:
      - "80:80"
    networks:
      - my-network

  express-server:
    build:
      context: ./express-server
    ports:
      - "3001:3001"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - express-server

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    networks:
      - my-network
    depends_on:
      - prometheus

networks:
  my-network:
    driver: bridge

