version: '3.8'

services:
  reactapp:
    image: ${DOCKER_IMAGE}
    ports:
      - "80:80"
    my-network:
    driver: bridge
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
 
  express-server:
    build:
      context: ./express-server
    ports:
      - "3001:3001"
    my-network:
    driver: bridge

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    my-network:
    driver: bridge

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    my-network:
    driver: bridge
    depends_on:
      - express-server
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    my-network:
    driver: bridge
    depends_on:
      - prometheus

networks:
  my-network:
    driver: bridge
