global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'express-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['express-server:3001']
  - job_name: 'react_app_health'
    static_configs:
      - targets: ['express-server:3001/health']
rule_files:
  - "alert.rules.yml"


